### ISSUE TITLE
Flutter 3.7 error

### ISSUE THREAD

**Issue by rlbartz** [tmthecoder/dargon2#15]
When running argon2_flutter plugin with flutter 3.7.0 (previous version works well) it breaks with the following error (Only on web):

ChromeProxyService: Failed to evaluate expression 'require': InternalError: Expression evaluation in async frames is not supported. No frame with index 15
Error: Mismatched anonymous define() module: function() { return CanvasKitInit; }

File: Argon2.dart
Funcion: _registerRequire() 

Steps to reproduce:
- Create a flutter project
- Import argon2_flutter plugin
- Build for web

**Comment by tmthecoder** [comment]
Hi, does this help at all: https://stackoverflow.com/questions/71521564/chromeproxyservice-failed-to-evaluate-expression-handleprimarypointerinterna

If not, it seems like a debug only error. Can you see if it comes up in a release build (Test argon2 functionality in a release web app?)

**Comment by rlbartz** [comment]
I tested in release web, and it works. In debug mode, just works if I downgrade flutter to 3.3.10 (event with fresh install of flutter sdk 3.7.0).
I tried all tips on this link (https://stackoverflow.com/questions/71521564/chromeproxyservice-failed-to-evaluate-expression-handleprimarypointerinterna), but it doesn't helped.
Any way to work around this error in debug mode in order to be able to test application before release?

**Comment by Yavnik** [comment]
I'm getting similar error in web debug after upgrading to Flutter 3.7 on the function argon2.hashPasswordString()

[DArgon2ErrorCode.ARGON2_UNKNOWN_ERRO… read properties of undefined (reading 'argon2i')

**Comment by tmthecoder** [comment]
Hi,

I'm looking into this right now. The reading properties of undefined is due to the prior error's cascading effects (argon2's web library isn't loaded, so the objects are undefined)

**Comment by tmthecoder** [comment]
Fixed with 3.2.0

**Comment by rlbartz** [comment]
Thank you. It's working properly now.

**Comment by Yavnik** [comment]
@tmthecoder Thank you for the quick fix, Tejas. Much appreciated.
