### ISSUE TITLE
Generated Salt with newSalt(int length) has always a length of 16

### ISSUE THREAD

**Issue by Anais-B** [tmthecoder/dargon2#18]
Hi,

Thank you for the library, it is very helpful.

However, I can't generate a new salt with the length I want, the function Salt.newSalt() always return a salt with length of 16, even if the length provided in parameters is different.

In fact, it appears that the length of 16 has been hardcoded in the Salt class (dargon2/dargon2_interface/lib/src/salt.dart) in the newSalt() function :

<img width="505" alt="Screenshot 2023-04-17 at 10 54 38" src="https://user-images.githubusercontent.com/94113543/232436921-5b34ae82-fe23-4043-b3f3-151d11d4c5c5.png">

**Comment by tmthecoder** [comment]
Ah my bad, that completely slipped past me. Thanks for the catch! Should be fixed by running `dart pub upgrade`!
