### ISSUE TITLE
Missing mode `argon2d` and `argon2id`

### ISSUE THREAD

**Issue by Nukesor** [tmthecoder/dargon2#3]
Hi :)

First of all, thanks for providing this library, it has been a great help so far!
Before I continue, I want to provide you with a little bit of background on what we're trying to accomplish.

The current setup is like this: We have a Mobile Application -> Backend Server setup. Under normal circumstances the mobile app uses the available internet connection to authorize and login users. However, we also want to offer offline login, which requires partially syncing argon2 ciphers generated by the backend and verifying them in the frontend.

According to the new spec, there are exist two "new" modes for argon2: https://www.password-hashing.net/argon2-specs.pdf
They have been added to the spec December 2015.

`Argon2id` was introduced to offer a hybrid implementation for `argon2i` and `argon2d`, which offers the best of both worlds.

Is it planned to introduce this spec into this library :)?

**Comment by Nukesor** [comment]
Ok. I browsed a little more through your documentation and found this:
https://pub.dev/documentation/dargon2_core/latest/dargon2_core/Argon2Type.html

It looks like I was wrong and the spec is already implemented :D
However, it seems that `argon2d` and `argon2id` aren't correctly parsed from PHC format strings in your library.

This is a valid `argon2id` string for the password `password`:
```
var password = 'password';
var encodedString= r"$argon2id$v=19$m=8,t=1,p=1$j3ROtWZmNdCfHQi0Tn7jfg$TeYJ2begJx9CbHsEIwmiQtB35Y0fVZX7hDYv8jItpZQ";
```

Trying to decode and verify it with:
```
    var verified = await argon2.verifyHashString(password, encodedString);
```

results in this error:
```
Unhandled exception:
[DArgon2ErrorCode.ARGON2_DECODING_FAIL] Decoding failed
#0      DArgon2.verifyHashBytesSync (package:dargon2_core/src/argon2.dart:258:7)
#1      DArgon2.verifyHashStringSync (package:dargon2_core/src/argon2.dart:235:12)
#2      DArgon2.verifyHashString (package:dargon2_core/src/argon2.dart:212:12)
#3      dargon2_example (file:///home/nuke/work/playground/dart_testing/bin/dart_testing.dart:82:33)
#4      main (file:///home/nuke/work/playground/dart_testing/bin/dart_testing.dart:76:11)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by Nukesor** [comment]
If I change the query string to `argon2i` instead of `argon2id`, this error pops up instead:
```
[DArgon2ErrorCode.ARGON2_VERIFY_MISMATCH] The password does not match the supplied hash
#0      DArgon2.verifyHashBytesSync (package:dargon2_core/src/argon2.dart:258:7)
#1      DArgon2.verifyHashStringSync (package:dargon2_core/src/argon2.dart:235:12)
#2      DArgon2.verifyHashString (package:dargon2_core/src/argon2.dart:212:12)
#3      dargon2_example (file:///home/nuke/work/playground/dart_testing/bin/dart_testing.dart:82:33)
#4      main (file:///home/nuke/work/playground/dart_testing/bin/dart_testing.dart:76:11)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

This looks like an expected and well-formed error.
From my observerations, I just assumed that you didn't yet implement `argon2d` and `argon2id`, but my current guess is that the parser just doesn't recognize these other modes yet?

**Comment by tmthecoder** [comment]
@Nukesor Argon2i and Argon2id are both implemented in hashing and verification. If you take a look at the examples and/or documentation of the verification methods, there is an optional 'mode' parameter that allows you to specify which of the 3 is used. 

You are correct that it doesn't parse it from the encoded hash. I wasn't sure if it was a wanted feature, though if it is I can add it in for a future release

**Comment by Nukesor** [comment]
Thanks for the fast help, the `type` was indeed what I was looking for.

I think it would be a good idea to determine the argon2 mode from the PHC string as well, as all other parameters are deducted from it as well. This behavior kind of confused me a little :)

**Comment by tmthecoder** [comment]
@Nukesor Glad to help! I'll definitely take a look at adding it. Might leave type in but if not specified it'll auto deduce the type. I'll close this issue for now though.
