### ISSUE TITLE
[dargon2_flutter] FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by Meap316** [tmthecoder/dargon2#6]
Hi, I'm trying to use the package dargon2_flutter. But when I tried to build my project it failed to build. Here's the log when i run the flutter using "flutter run -v".

![2022-03-15_15-55](https://user-images.githubusercontent.com/66449267/158341536-d3461dc0-3398-4e08-bb4f-4f20b5c2de09.png)

**Comment by tmthecoder** [comment]
@Meap316 do you have ndk installed on your device? Since dargon2_flutter uses the C library of argon2, ndk is required for the build

**Comment by Meap316** [comment]
Thank you, the problem is fixed now.

The problem was the corrupted NDK, I deleted all folder inside my ndk folder which is located on my android SDK folder. Then I try to rebuild the app and it went smoothly.
