### ISSUE TITLE
[dargon2] Invalid argument(s): Failed to load dynamic library

### ISSUE THREAD

**Issue by AaronFeickert** [tmthecoder/dargon2#8]
Using `dargon2: ^3.2.0` on an Ubuntu 22.04 variant with `Dart SDK version: 2.17.5 (stable) (Unknown timestamp) on "linux_x64"` results in an error on `dart run`, but not on `dart test`.

Here is sample source:
```
import 'package:dargon2/dargon2.dart';

void main() async {
  await argon2.hashPasswordBytes(
    <int>[0,1,2],
    salt: Salt(<int>[3,4]),
  );
}
```

Running `dart run` produces the following output:
```
Building package executable... 
Built dargon2_test:dargon2_test.
Unhandled exception:
Invalid argument(s): Failed to load dynamic library '/home/test/dargon2-test/.dart_tool/pub/bin/dargon2_testlibargon2-linux.so': /home/test/dargon2-test/.dart_tool/pub/bin/dargon2_testlibargon2-linux.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      DartLibLoader.loadLib (package:dargon2/src/native/dart_lib_loader.dart:24:27)
#3      new LocalBinder._ (package:dargon2_core/src/native/local_binder.dart:155:31)
#4      LocalBinder.initialize (package:dargon2_core/src/native/local_binder.dart:130:38)
#5      new DArgon2Native (package:dargon2_core/src/native/dargon2_native.dart:19:17)
#6      argon2 (package:dargon2/src/argon2.dart:11:16)
#7      argon2 (package:dargon2/src/argon2.dart)
#8      main (file:///home/test/dargon2-test/bin/dargon2_test.dart:4:9)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

Putting the same code into a test function and then running `dart test` does not crash, but correctly complains that the salt is too short.

**Comment by tmthecoder** [comment]
Hello, thanks for bringing this up. I'm able to replicate this on my Mac too. It seems like something changed with the URI resolution. I'll need some time to dig deeper into this since I'm pretty unsure as to what the reason that this works on testing but not an actual run is.

**Comment by tmthecoder** [comment]
@AaronFeickert After looking a little, I don't think this is an error in the plugin. If I do `dart run path/to/main.dart` it works. Can you confirm the behavior is the same on your end?

**Comment by AaronFeickert** [comment]
@tmthecoder: I can confirm that `dart run bin/dargon2_test.dart` works for me.

**Comment by tmthecoder** [comment]
@AaronFeickert Perfect, thanks! Do you want me to open an issue on dart's main repo (since I don't think this is fixable in dargon2) or would you prefer to do it?

**Comment by AaronFeickert** [comment]
@tmthecoder: I'm pretty new to Dart, and am not sure how useful my issue reporting would be. If it's not too much trouble, I'm sure you would do a much better job of it!

Thanks for the prompt response.

**Comment by tmthecoder** [comment]
@AaronFeickert No worries, I'll open an issue on dart's main repo. Glad to help!

**Comment by AaronFeickert** [comment]
Thanks! Please link or reference the issue if convenient; I'd like to follow its progress.

**Comment by tmthecoder** [comment]
@AaronFeickert It's linked to this issue in the dart repo one. Here's the link: https://github.com/dart-lang/sdk/issues/49417

**Comment by AaronFeickert** [comment]
I encountered a similar error when running `flutter test` with `dargon2_flutter`.

**Comment by tmthecoder** [comment]
@AaronFeickert testing with flutter test and dargon2_flutter only works for integration tests since FFI libraries aren't loaded without the mobile emulator environment

**Comment by AaronFeickert** [comment]
@tmthecoder Thanks! I was actually able to get tests running by building the Argon2 reference implementation and copying the compiled library to the location referenced in the error.

**Comment by tmthecoder** [comment]
@AaronFeickert oh, good to know! I haven't actually thought of trying that.

**Comment by AaronFeickert** [comment]
@tmthecoder A similar approach worked as a temporary fix for [this issue](https://github.com/tmthecoder/dargon2/issues/9), which led me to try it here.

**Comment by tmthecoder** [comment]
@AaronFeickert The above PR fixes it on my end. Can you verify the same. The ref should be `fix-dart-run-failure`

**Comment by AaronFeickert** [comment]
@tmthecoder Will check presently.

**Comment by AaronFeickert** [comment]
@tmthecoder Success on Ubuntu 22.04 (`test` and `run`). Need earlier version confirmation?

**Comment by tmthecoder** [comment]
@AaronFeickert Perfect! I'll merge and release shortly. Thanks again!

**Comment by tmthecoder** [comment]
@AaronFeickert Just published with dargon2 3.2.1

**Comment by AaronFeickert** [comment]
@tmthecoder Great! Thanks again.

**Comment by AaronFeickert** [comment]
@tmthecoder This issue still remains for `dargon2_flutter`.

**Comment by tmthecoder** [comment]
@AaronFeickert are you referring to the lookup failing when running non integration tests?

**Comment by AaronFeickert** [comment]
@tmthecoder Yes! Did your earlier comment mean that this is an inherent limitation that cannot be addressed? Perhaps I misunderstood.

**Comment by tmthecoder** [comment]
@AaronFeickert it's something that shouldn't be addressed in my opinion since that's just a testing fix and would add additional weight on the Flutter package when it wouldn't actually be used in any built applications (since desktop FFI has its own build process for Flutter)

**Comment by AaronFeickert** [comment]
@tmthecoder Any particular recommendations for using the Flutter plugin in practice in order to write and run tests easily? Having to copy the compiled library to test seems like it should be unnecessary.

**Comment by tmthecoder** [comment]
@AaronFeickert any integration testing with flutter's built in integration testing system will give you the best results. Normal unit testing only loads dart code, so it's not possible to run the native library loading per platform (since it's handled outside of dart code). Integration tests spin up the entire application, so that should be your best bet

For an example, take a look at the example's integration test file in dargon2_flutter's directory

**Comment by AaronFeickert** [comment]
@tmthecoder Thanks for the information!
