### ISSUE TITLE
[dargon2] Crash on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by AaronFeickert** [tmthecoder/dargon2#9]
Using `dargon2: ^3.2.0` on Ubuntu 20.04.3 LTS with Dart SDK 2.17.5 results in a crash.

Here is sample source:
```
import 'package:dargon2/dargon2.dart';

void main() async {
  await argon2.hashPasswordBytes(
    <int>[0,1,2],
    salt: Salt.newSalt(),
  );
}
```

Running this code (applying the temporary path fix from [this issue](https://github.com/tmthecoder/dargon2/issues/8#issuecomment-1177620490)) gives the following output:
```
===== CRASH =====
si_signo=Illegal instruction(4), si_code=2, si_addr=0x7efdd8c5da58
version=2.17.5 (stable) (Unknown timestamp) on "linux_x64"
pid=33638, thread=33647, isolate_group=main(0x56193f53b000), isolate=main(0x56193f5cd800)
isolate_instructions=56193d650060, vm_instructions=56193d650060
  pc 0x00007efdd8c5da58 fp 0x00007efdd40fd050 /home/test/.pub-cache/hosted/pub.dartlang.org/dargon2-3.2.0/lib/src/blobs/libargon2-linux.so+0x3a58
  pc 0x00007efdd8c5cd54 fp 0x00007efdd40fd290 /home/test/.pub-cache/hosted/pub.dartlang.org/dargon2-3.2.0/lib/src/blobs/libargon2-linux.so+0x2d54
-- End of DumpStackTrace
  pc 0x0000000000000000 fp 0x00007efdd40fd398 sp 0x0000000000000000 [Optimized] 69814359965696
  pc 0x00007efdd1e69323 fp 0x00007efdd40fd428 sp 0x00007efdd40fd3a8 [Optimized] FfiTrampoline
  pc 0x00007efdd1e645a3 fp 0x00007efdd40fd5e0 sp 0x00007efdd40fd438 [Unoptimized] DArgon2Native.hashPasswordBytesSync
  pc 0x00007efdd1e639d1 fp 0x00007efdd40fd680 sp 0x00007efdd40fd5f0 [Unoptimized] DArgon2Native.hashPasswordBytes
  pc 0x00007efdd1e6386a fp 0x00007efdd40fd778 sp 0x00007efdd40fd690 [Unoptimized] DArgon2Native.hashPasswordBytes
  pc 0x00007efdd1e247cc fp 0x00007efdd40fd7e0 sp 0x00007efdd40fd788 [Unoptimized] main
  pc 0x00007efdd1e23d6f fp 0x00007efdd40fd820 sp 0x00007efdd40fd7f0 [Unoptimized] main
  pc 0x00007efdd1e239c9 fp 0x00007efdd40fd848 sp 0x00007efdd40fd830 [Unoptimized] main
  pc 0x00007efdd1e238f9 fp 0x00007efdd40fd8a8 sp 0x00007efdd40fd858 [Unoptimized] _Closure@0150898.dyn:call
  pc 0x00007efdd1e22790 fp 0x00007efdd40fd8e0 sp 0x00007efdd40fd8b8 [Unoptimized] _delayEntrypointInvocation@1026248.<anonymous closure>
  pc 0x00007efdd1e2251c fp 0x00007efdd40fd948 sp 0x00007efdd40fd8f0 [Unoptimized] _Closure@0150898.dyn:call
  pc 0x00007efdd1e21d93 fp 0x00007efdd40fd998 sp 0x00007efdd40fd958 [Unoptimized] _RawReceivePortImpl@1026248._handleMessage@1026248
  pc 0x00007efdd8302a0c fp 0x00007efdd40fda10 sp 0x00007efdd40fd9a8 [Stub] InvokeDartCode
Aborted (core dumped)
```

As a test, I confirmed that I was able to build the [reference implementation](https://github.com/P-H-C/phc-winner-argon2) and run its command-line tool. Further, copying (with a rename) that compiled library to the `.pub-cache/[...]/blobs/` directory allows the example code to run properly.

**Comment by AaronFeickert** [comment]
Interestingly, GitHub Actions [reports](https://github.com/actions/virtual-environments#available-environments) that Ubuntu 20.04 is the current `ubuntu-latest` environment, and I see that this repository's CI build [uses it](https://github.com/tmthecoder/dargon2/blob/main/.github/workflows/dargon2_library-builder.yml#L13).

**Comment by tmthecoder** [comment]
@AaronFeickert Does testing still work? Or is it both testing and running causing the crash? Since the tests on CI seem to pass fine

**Comment by AaronFeickert** [comment]
@tmthecoder Testing fails. I put that sample code directly into a test and ran `dart test`, which produced the same type of error.

**Comment by tmthecoder** [comment]
@AaronFeickert That's very weird, the CI seems to run tests fine, the latest branch's test runs all succeeded (ubuntu included).


If you set up the pubspec entry as:

```
dargon2:
  git:
    url: https://github.com/tmthecoder/dargon2
    path: dargon2
```

and run `pub get` and test/run, does the same error come up?

**Comment by AaronFeickert** [comment]
@tmthecoder Could it be a difference in build environment between the `ubuntu-latest` environment and a fully-updated Ubuntu 20.04.3 LTS installation?

My colleague tested on his Ubuntu 20.04 installation, and my testing was done on a clean VM (with all available updates applied). Errors on both.

**Comment by AaronFeickert** [comment]
@tmthecoder Same error after updating `pubspec.yaml` as requested.

**Comment by AaronFeickert** [comment]
@tmthecoder I see that `ubuntu-latest` lists [two versions](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#language-and-runtime) of `gcc`, the more recent of which is not included on a default Ubuntu 20.04.3 LTS installation (with `build-essential` added). Could this be related?

**Comment by tmthecoder** [comment]
@AaronFeickert Can you update and check one more time? I ran the builder to reupload a library off of the latest argon2 reference repo commit

**Comment by AaronFeickert** [comment]
@tmthecoder Ran `dart pub cache repair` to download the latest from the repository, and `dart test`. Same error.

**Comment by tmthecoder** [comment]
@AaronFeickert Interesting, now the CI's ubuntu test is broken too after building

**Comment by AaronFeickert** [comment]
@tmthecoder That's odd, since I was able to do a manual build from the reference implementation, copy it to the expected location, and run successfully.

**Comment by AaronFeickert** [comment]
@tmthecoder Just tried a reference implementation build again, and it worked after copying the resulting compiled library to the appropriate `.pub-cache` location.

**Comment by AaronFeickert** [comment]
@tmthecoder The only thing I can think of as a difference between the environments could be that `ubuntu-latest` is (presumably?) using `gcc 10.3.0`, whereas the default Ubuntu 20.04.3 LTS installation with `build-essential` is using `gcc 9.4.0`.

**Comment by tmthecoder** [comment]
@AaronFeickert I can try to see if that leads to a fix anywhere. This still works from dart pub on ubuntu 22.04 where the first issue was filed from?

**Comment by AaronFeickert** [comment]
@tmthecoder Using the `git` reference to `dargon2` on Ubuntu 22.04 tests just fine.

**Comment by AaronFeickert** [comment]
@tmthecoder I used `gcc 10.3.0` for a reference implementation build on Ubuntu 20.04.3 LTS and copied the resulting library into the cache, and testing still worked. So it seems unrelated to that.

**Comment by tmthecoder** [comment]
@AaronFeickert Are you able to test on the branch now? It should work. If it's possible would you be able to test on both 22.04 and 20.04 to make sure both still work?

**Comment by AaronFeickert** [comment]
@tmthecoder Will test shortly on both! I also have VMs for older LTS releases, depending how far back you intend to support.

**Comment by tmthecoder** [comment]
@AaronFeickert I'd say If this works on 20.04 I'd love to have you test farther back until it doesn't work. I don't think I'll personally add support but can put up a guide to replace the `.so` in the case they encounter a crash

**Comment by AaronFeickert** [comment]
@tmthecoder Still works on 22.04. Still crashes on 20.04.3 LTS after `dart pub cache clean && dart pub get && dart test`.

**Comment by tmthecoder** [comment]
@AaronFeickert Not sure what could cause this now since I built on a 20.04.1 Ubuntu server machine and pushed it up to GitHub. Any ideas?

**Comment by AaronFeickert** [comment]
@tmthecoder Looks like it's still grabbing commit `26c75d`, despite me nuking the lockfile...

**Comment by tmthecoder** [comment]
@AaronFeickert Ah wait make sure you set `ref: update-dargon2-libraries`

**Comment by AaronFeickert** [comment]
@tmthecoder Success on Ubuntu 20.04.3 LTS! Testing works correctly as expected. Running sample code with the `dart run path/to/main.dart` fix also works.

**Comment by AaronFeickert** [comment]
@tmthecoder Also happy to report success on Ubuntu 18.04.6 LTS.

**Comment by AaronFeickert** [comment]
@tmthecoder The Dart SDK [only supports](https://dart.dev/get-dart#linux) Ubuntu LTS versions under [standard support](https://wiki.ubuntu.com/Releases), which excludes Ubuntu 16.04.7 LTS and earlier. So your fix works on all versions that the Dart SDK supports.

**Comment by tmthecoder** [comment]
@AaronFeickert Alright, that's great to hear! I also heard back on #8, so I'll have a fix up there soon. After that's set I'll push a release to `pub.dev`

Thank you so much for all of the help!

**Comment by AaronFeickert** [comment]
@tmthecoder Awesome! Happy to help. Many thanks for your prompt response.
